/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.MecanicoModel;
import data.MecanicoData;
import javax.swing.JOptionPane;
import model.MecanicoModel;
import view.JfPrincipal;

/**
 *
 * @author andre
 */
public class JfPrincipal extends javax.swing.JFrame {

    private MecanicoModel obj;

    /**
     * Creates new form JfPrincipal
     */
    public JfPrincipal() {
        initComponents();
        obj = new MecanicoModel();
    }

    public JfPrincipal(MecanicoModel obj) {
        this();
        this.obj = obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbCriarOS = new javax.swing.JButton();
        jbNovoVeiculo = new javax.swing.JButton();
        jbNovoServico = new javax.swing.JButton();
        jbNovoMecanico = new javax.swing.JButton();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jbNovoClienteFisico = new javax.swing.JButton();
        jbNovoClienteJuridico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Mecânica");

        jbCriarOS.setText("Criar OS");
        jbCriarOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarOSActionPerformed(evt);
            }
        });

        jbNovoVeiculo.setText("Novo Veículo");
        jbNovoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoVeiculoActionPerformed(evt);
            }
        });

        jbNovoServico.setText("Novo Serviço");
        jbNovoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoServicoActionPerformed(evt);
            }
        });

        jbNovoMecanico.setText("Novo Mecânico");
        jbNovoMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoMecanicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        jbNovoClienteFisico.setText("Novo Cliente Físico");
        jbNovoClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoClienteFisicoActionPerformed(evt);
            }
        });

        jbNovoClienteJuridico.setText("Novo Cliente Jurídico");
        jbNovoClienteJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoClienteJuridicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbCriarOS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNovoClienteFisico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbNovoServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNovoClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jbNovoVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNovoMecanico, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addComponent(jdpPrincipal))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jbCriarOS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbNovoClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbNovoClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbNovoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbNovoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbNovoMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoServicoActionPerformed
        jifServico janelaServico = new jifServico();
        jdpPrincipal.add(janelaServico);
        janelaServico.setVisible(true);
    }//GEN-LAST:event_jbNovoServicoActionPerformed

    private void jbNovoClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoClienteFisicoActionPerformed
        jifClienteFisico janelaClienteF = new jifClienteFisico();
        jdpPrincipal.add(janelaClienteF);
        janelaClienteF.setVisible(true);
    }//GEN-LAST:event_jbNovoClienteFisicoActionPerformed

    private void jbNovoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoVeiculoActionPerformed
        jifVeiculo janelaVeiculo = new jifVeiculo();
        jdpPrincipal.add(janelaVeiculo);
        janelaVeiculo.setVisible(true);
    }//GEN-LAST:event_jbNovoVeiculoActionPerformed

    private void jbCriarOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarOSActionPerformed
        jifOS janelaOS = new jifOS();
        jdpPrincipal.add(janelaOS);
        janelaOS.setVisible(true);
    }//GEN-LAST:event_jbCriarOSActionPerformed

    private void jbNovoMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoMecanicoActionPerformed
        jifMecanico janelaMecanico = new jifMecanico();
        jdpPrincipal.add(janelaMecanico);
        janelaMecanico.setVisible(true);
    }//GEN-LAST:event_jbNovoMecanicoActionPerformed

    private void jbNovoClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoClienteJuridicoActionPerformed
        jifClienteJuridico janelaClienteJ = new jifClienteJuridico();
        jdpPrincipal.add(janelaClienteJ);
        janelaClienteJ.setVisible(true);
    }//GEN-LAST:event_jbNovoClienteJuridicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbCriarOS;
    private javax.swing.JButton jbNovoClienteFisico;
    private javax.swing.JButton jbNovoClienteJuridico;
    private javax.swing.JButton jbNovoMecanico;
    private javax.swing.JButton jbNovoServico;
    private javax.swing.JButton jbNovoVeiculo;
    private javax.swing.JDesktopPane jdpPrincipal;
    // End of variables declaration//GEN-END:variables
}
