/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.ClienteData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ClientePJModel;

/**
 *
 * @author andre
 */
public class jifClienteJuridico extends javax.swing.JInternalFrame {

    private ClientePJModel obj;
    private ClienteData DAO;
    private int acao;

    ArrayList<ClientePJModel> listaclientesjuridico;

    public jifClienteJuridico() {
        initComponents();
        obj = new ClientePJModel();
        try {
            DAO = new ClienteData();
        } catch (Exception ex) {
            Logger.getLogger(jifClienteJuridico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNome = new javax.swing.JTextField();
        jtfCNPJ = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbClienteJuridico = new javax.swing.JTable();
        jbEditar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbExcluir = new javax.swing.JButton();
        jtfTelefone = new javax.swing.JTextField();
        jtfBuscaCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jbLimpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jlIdClienteJur = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfIE = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jtbClienteJuridico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CNPJ", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbClienteJuridico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbClienteJuridicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbClienteJuridico);

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefone:");

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jtfBuscaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscaClienteKeyReleased(evt);
            }
        });

        jLabel6.setText("Endereço:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Pessoa Física");

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jLabel7.setText("Busca:");

        jLabel2.setText("Nome:");

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("CNPJ:");

        jlIdClienteJur.setText("0");

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jLabel3.setText("IE:");

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbExcluir)
                                    .addComponent(jbNovo))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbLimpar)
                                        .addGap(44, 44, 44)
                                        .addComponent(jbCancelar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbSalvar)
                                        .addGap(68, 68, 68)
                                        .addComponent(jbEditar))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfIE))
                                .addComponent(jlIdClienteJur)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                        .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jlIdClienteJur)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfIE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbEditar)
                    .addComponent(jbNovo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar)
                    .addComponent(jbCancelar)
                    .addComponent(jbExcluir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jtfBuscaCliente.setEnabled(false);
        jtbClienteJuridico.setEnabled(false);
        jtfNome.setEnabled(true);
        jtfEndereco.setEnabled(true);
        jtfTelefone.setEnabled(true);
        jtfCNPJ.setEnabled(true);
        jtfIE.setEnabled(true);
        acao = 1;
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    if (acao == 1) {
                        if (DAO.incluir(obj)) {
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso!",
                                    "Sistema", JOptionPane.INFORMATION_MESSAGE);
                            //salvar no banco
                            jbCancelarActionPerformed(evt);
                        }
                    }
                    if (acao == 2) {
                        if (DAO.editar(obj)) {
                            JOptionPane.showMessageDialog(this, "Editado com sucesso!",
                                    "Sistema", JOptionPane.INFORMATION_MESSAGE);
                            //salvar no banco
                            jbCancelarActionPerformed(evt);
                        }
                    }
                }
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar:" + erro.getMessage(), "Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        acao = 2; //editar
        jtfNome.setEnabled(true);
        jtfEndereco.setEnabled(true);
        jtfTelefone.setEnabled(true);
        jtfCNPJ.setEnabled(true);
        jtfIE.setEnabled(true);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbNovo.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(this, "Deseja excluir esse serviço?") == JOptionPane.YES_OPTION) {
                if (DAO.excluir(obj, Integer.parseInt(jlIdClienteJur.getText()))) {
                    JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
                    jbCancelarActionPerformed(evt);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        try {
            extras.TrataFormulario.limparCampos(this);
        } catch (Exception ex) {
            Logger.getLogger(jifServico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jtfBuscaCliente.setEnabled(true);
        jtbClienteJuridico.setEnabled(true);
        jtfNome.setEnabled(false);
        jtfEndereco.setEnabled(false);
        jtfTelefone.setEnabled(false);
        jtfCNPJ.setEnabled(false);
        jtfIE.setEnabled(false);
        jtfNome.setText("");
        jtfEndereco.setText("");
        jtfTelefone.setText("");
        jtfCNPJ.setText("");
        jtfIE.setText("");
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtbClienteJuridicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbClienteJuridicoMouseClicked
        int linhaSelecionada = jtbClienteJuridico.getSelectedRow();
        if (linhaSelecionada > -1) {
            jlIdClienteJur.setText("" + listaclientesjuridico.get(linhaSelecionada).getIdCliente());
            jtfNome.setText("" + listaclientesjuridico.get(linhaSelecionada).getNome());
            jtfEndereco.setText("" + listaclientesjuridico.get(linhaSelecionada).getEndereco());
            jtfTelefone.setText("" + listaclientesjuridico.get(linhaSelecionada).getTelefone());
            jtfCNPJ.setText("" + listaclientesjuridico.get(linhaSelecionada).getCNPJ());
            jtfIE.setText("" + listaclientesjuridico.get(linhaSelecionada).getIE());
            jbEditar.setEnabled(true);
            jbExcluir.setEnabled(true);
        } else {
            jbEditar.setEnabled(false);
            jbExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_jtbClienteJuridicoMouseClicked

    private void jtfBuscaClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscaClienteKeyReleased
        try {
            DefaultTableModel mp = (DefaultTableModel) jtbClienteJuridico.getModel();
            mp.setNumRows(0);
            if (jtfBuscaCliente.getText().length() > 1) {
                listaclientesjuridico = DAO.pesquisarClientePJ(jtfBuscaCliente.getText());
                for (ClientePJModel j : listaclientesjuridico) {
                    mp.addRow(new String[]{"" + j.getNome(), j.getCNPJ(), j.getTelefone()});
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jtfBuscaClienteKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlIdClienteJur;
    private javax.swing.JTable jtbClienteJuridico;
    private javax.swing.JTextField jtfBuscaCliente;
    private javax.swing.JTextField jtfCNPJ;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfIE;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfTelefone;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos() {
        String msg = "";
        if (jtfNome.getText().length() < 3 || jtfNome.getText().length() > 100) {
            msg += "\nO campo Nome deve conter entre 3 e 100 caracteres";
        }

        if (jtfEndereco.getText().length() < 3 || jtfEndereco.getText().length() > 200) {
            msg += "\nO campo Endereço deve conter entre 3 e 200 caracteres";
        }

        if (jtfTelefone.getText().length() < 1 || jtfTelefone.getText().length() > 20) {
            msg += "\nO campo telefone deve conter entre 1 e 20 caracteres";
        }

        if (jtfCNPJ.getText().length() < 1 || jtfCNPJ.getText().length() > 20) {
            msg += "\nO campo CNPJ deve conter entre 1 e 15 caracteres";
        }

        if (jtfIE.getText().length() < 1 || jtfIE.getText().length() > 20) {
            msg += "\nO campo Inscrição Estadual deve conter entre 1 e 15 caracteres";
        }

        if (msg.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Os campos abaixo precisam de atenção:"
                    + msg, "Atenção", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    private boolean preencherObjeto() throws Exception {
        obj.setIdCliente(Integer.parseInt(jlIdClienteJur.getText()));
        obj.setNome(jtfNome.getText());
        obj.setEndereco(jtfEndereco.getText());
        obj.setTelefone(jtfTelefone.getText());
        obj.setCNPJ(jtfCNPJ.getText());
        obj.setIE(jtfIE.getText());
        return true;
    }

}
