/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.MecanicoData;
import model.MecanicoModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author andre
 */
public class jifMecanico extends javax.swing.JInternalFrame {

    private MecanicoModel obj;
    private MecanicoData DAO;
    private int acao;
    
    ArrayList<MecanicoModel> listamecanicos;

    /**
     * Creates new form JifCadUsuario
     */
    public jifMecanico() {
        initComponents();
        obj = new MecanicoModel();
        try {
            DAO = new MecanicoData();
        } catch (Exception ex) {
            Logger.getLogger(jifMecanico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtbMecanico = new javax.swing.JTable();
        jtfBuscaMecanico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbNovo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jtfNome = new javax.swing.JTextField();
        jbEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jtfEspecialidade = new javax.swing.JTextField();
        jbLimpar = new javax.swing.JButton();
        jlIdMecanico = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jtbMecanico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Especialidade", "Usuário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbMecanico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbMecanicoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbMecanico);

        jtfBuscaMecanico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscaMecanicoKeyReleased(evt);
            }
        });

        jLabel4.setText("Busca:");

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jLabel1.setText("Cadastro de Mecânicos");

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jLabel3.setText("Especialidade:");

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlIdMecanico.setText("0");

        jLabel5.setText("Usuário:");

        jLabel6.setText("Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNome)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfEspecialidade))
                    .addComponent(jlIdMecanico)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfUsuario)
                            .addComponent(jpfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfBuscaMecanico))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbExcluir)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbEditar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbLimpar)
                                        .addGap(15, 15, 15))))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNovo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlIdMecanico)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jpfSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbEditar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExcluir)
                    .addComponent(jbCancelar)
                    .addComponent(jbLimpar))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBuscaMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jtfBuscaMecanico.setEnabled(false);
        jtbMecanico.setEnabled(false);
        jtfEspecialidade.setEnabled(true);
        jtfNome.setEnabled(true);
        jtfUsuario.setEnabled(true);
        jpfSenha.setEnabled(true);
        acao=1;
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jtfBuscaMecanico.setEnabled(true);
        jtbMecanico.setEnabled(true);
        jtfNome.setEnabled(false);
        jtfUsuario.setEnabled(false);
        jpfSenha.setEnabled(false);
        jtfEspecialidade.setEnabled(false);
        jtfNome.setText("");
        jtfEspecialidade.setText("");
        jtfUsuario.setText("");
        jpfSenha.setText("");
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        acao = 2; //editar
        jtfNome.setEnabled(true);
        jtfEspecialidade.setEnabled(true);
        jtfUsuario.setEnabled(true);
        jpfSenha.setEnabled(true);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbNovo.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    if (acao == 1) {
                        if (DAO.incluir(obj)) {
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso!",
                                    "Sistema", JOptionPane.INFORMATION_MESSAGE);
                            //salvar no banco
                            jbCancelarActionPerformed(evt);
                        }
                    }
                    if (acao == 2) {
                        if (DAO.editar(obj)) {
                            JOptionPane.showMessageDialog(this, "Editado com sucesso!",
                                    "Sistema", JOptionPane.INFORMATION_MESSAGE);
                            //salvar no banco
                            jbCancelarActionPerformed(evt);
                        }
                    }
                }
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar:" + erro.getMessage(), "Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(this, "Deseja excluir esse mecânico?") == JOptionPane.YES_OPTION) {
                if (DAO.excluir(Integer.parseInt(jlIdMecanico.getText()))) {
                    JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
                    jbCancelarActionPerformed(evt);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        try {
            extras.TrataFormulario.limparCampos(this);
        } catch (Exception ex) {
            Logger.getLogger(jifMecanico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtfBuscaMecanicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscaMecanicoKeyReleased
        try {
            listamecanicos = DAO.pesquisar(jtfBuscaMecanico.getText());
            DefaultTableModel mp = (DefaultTableModel) jtbMecanico.getModel();
            mp.setNumRows(0);
            for (MecanicoModel u : listamecanicos) {
                mp.addRow(new String[]{"" + u.getNome(), u.getEspecialidade(), u.getUsuario()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar:" + e.getMessage());
        }
    }//GEN-LAST:event_jtfBuscaMecanicoKeyReleased

    private void jtbMecanicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbMecanicoMouseClicked
        int linhaSelecionada = jtbMecanico.getSelectedRow();
        if (linhaSelecionada > -1) {
            jlIdMecanico.setText("" + listamecanicos.get(linhaSelecionada).getIdMec());
            jtfNome.setText("" + listamecanicos.get(linhaSelecionada).getNome());
            jtfEspecialidade.setText("" + listamecanicos.get(linhaSelecionada).getEspecialidade());
            jtfUsuario.setText("" + listamecanicos.get(linhaSelecionada).getUsuario());
            jpfSenha.setText("" + listamecanicos.get(linhaSelecionada).getSenha());
            jbEditar.setEnabled(true);
            jbExcluir.setEnabled(true);
        } else {
            jbEditar.setEnabled(false);
            jbExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_jtbMecanicoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlIdMecanico;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTable jtbMecanico;
    private javax.swing.JTextField jtfBuscaMecanico;
    private javax.swing.JTextField jtfEspecialidade;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos() {
        String msg = "";
        if (jtfNome.getText().length() < 3 || jtfNome.getText().length() > 100) {
            msg += "\nO campo Nome deve conter entre 3 e 100 caracteres";
        }

        if (jtfEspecialidade.getText().length() < 3 || jtfEspecialidade.getText().length() > 100) {
            msg += "\nO campo Especialidade deve conter entre 3 e 100 caracteres";
        }
        
        if (jtfUsuario.getText().length() < 3 || jtfUsuario.getText().length() > 100) {
            msg += "\nO campo Usuário deve conter entre 3 e 100 caracteres";
        }
        
        if (jpfSenha.getText().length() < 5 || jpfSenha.getText().length() > 100) {
            msg += "\nO campo Senha deve conter entre 3 e 100 caracteres";
        }

        if (msg.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Os campos abaixo precisam de atenção:"
                    + msg, "Atenção", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    private boolean preencherObjeto() throws Exception {
        obj.setIdMec(Integer.parseInt(jlIdMecanico.getText()));
        obj.setNome(jtfNome.getText());
        obj.setEspecialidade(jtfEspecialidade.getText());
        obj.setUsuario(jtfUsuario.getText());
        obj.setSenha(jpfSenha.getText());
        return true;
    }

}
